language: ruby
rvm:
  # MRI
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.3.0
  # JRuby
  - jruby-9000
script:
  # Tests
  - ruby tests/pointy.rb
  - ruby tests/scribble.rb
  - ruby tests/chain.rb
  - ruby tests/apeirogon.rb
  - ruby tests/round.rb
  # Examples
  - ruby examples/search/Search.rb