language: ruby
rvm:
  # MRI
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.3.0
  # JRuby
  - jruby-9000
script:
  # Tests
  - ruby tests/pointy.rb
  - ruby tests/scribble.rb
  - ruby tests/chain.rb
  - ruby tests/apeirogon.rb
  - ruby tests/round.rb
  # Examples
  - ruby examples/search/pb1.rb
  - ruby examples/search/pb2.rb
  - ruby examples/search/pb3.rb
  - ruby examples/search/pb4.rb
  - ruby examples/search/pb5.rb
  - ruby examples/goalrtree/pb1.rb
  - ruby examples/goalrtree/pb2.rb
  - ruby examples/goalrtree/pb3.rb
  - ruby examples/goalrtree/pb4.rb
  - ruby examples/goalrtree/pb5.rb
  - ruby examples/circular/circular.rb