name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7, '3.0', 3.1, 3.2, head, jruby-head, truffleruby-head]
      fail-fast: false
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    # Tests
    - run: ruby tests/pointy.rb
    - run: ruby tests/scribble.rb
    - run: ruby tests/chain.rb
    - run: ruby tests/apeirogon.rb
    - run: ruby tests/round.rb
    # Examples
    - run: ruby examples/search/pb1.rb
    - run: ruby examples/search/pb2.rb
    - run: ruby examples/search/pb3.rb
    - run: ruby examples/search/pb4.rb
    - run: ruby examples/search/pb5.rb
    - run: ruby examples/goalrtree/pb1.rb
    - run: ruby examples/goalrtree/pb2.rb
    - run: ruby examples/goalrtree/pb3.rb
    - run: ruby examples/goalrtree/pb4.rb
    - run: ruby examples/goalrtree/pb5.rb
    - run: ruby examples/circular/pb1.rb
    - run: ruby examples/circular/pb2.rb
    - run: ruby examples/circular/pb3.rb
    - run: ruby examples/circular/pb4.rb